/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwaremanagementshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Shatu
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
        
    public Home() {
        initComponents();
        jButtonSelect.setVisible(false);
        
        jLabelpass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jButtonHardware = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCalculator = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonManager = new javax.swing.JButton();
        jButtonEmployee = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonChangePassword = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();
        panel4 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jButtonAddUser = new javax.swing.JButton();
        jLabelpass = new javax.swing.JLabel();
        jButtonSelect = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonAddProduct = new javax.swing.JButton();
        jButtonSellProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Stock");

        jButtonHardware.setBackground(new java.awt.Color(0, 0, 51));
        jButtonHardware.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonHardware.setForeground(new java.awt.Color(102, 102, 255));
        jButtonHardware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/hardware.png"))); // NOI18N
        jButtonHardware.setText("Hardware");
        jButtonHardware.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonHardware.setIconTextGap(6);
        jButtonHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHardwareActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tools");

        jButtonCalculator.setBackground(new java.awt.Color(0, 51, 51));
        jButtonCalculator.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCalculator.setForeground(new java.awt.Color(102, 102, 255));
        jButtonCalculator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/calculator.png"))); // NOI18N
        jButtonCalculator.setText("Calculator");
        jButtonCalculator.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonCalculator.setIconTextGap(6);
        jButtonCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculatorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Administration");

        jButtonManager.setBackground(new java.awt.Color(51, 0, 0));
        jButtonManager.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonManager.setForeground(new java.awt.Color(102, 102, 255));
        jButtonManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/manager.png"))); // NOI18N
        jButtonManager.setText("Manager");
        jButtonManager.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonManager.setIconTextGap(6);
        jButtonManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManagerActionPerformed(evt);
            }
        });

        jButtonEmployee.setBackground(new java.awt.Color(51, 0, 0));
        jButtonEmployee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(102, 102, 255));
        jButtonEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/employee.png"))); // NOI18N
        jButtonEmployee.setText("Employee");
        jButtonEmployee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonEmployee.setIconTextGap(6);
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        jButtonCustomer.setBackground(new java.awt.Color(51, 0, 0));
        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCustomer.setForeground(new java.awt.Color(102, 102, 255));
        jButtonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/customer.png"))); // NOI18N
        jButtonCustomer.setText("Customer");
        jButtonCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonCustomer.setIconTextGap(6);
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("System");

        jButtonChangePassword.setBackground(new java.awt.Color(102, 255, 204));
        jButtonChangePassword.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButtonChangePassword.setForeground(new java.awt.Color(255, 0, 0));
        jButtonChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/changepassword.png"))); // NOI18N
        jButtonChangePassword.setText("Change Password");
        jButtonChangePassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonChangePassword.setIconTextGap(6);
        jButtonChangePassword.setPreferredSize(new java.awt.Dimension(117, 47));
        jButtonChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangePasswordActionPerformed(evt);
            }
        });

        jButtonLogOut.setBackground(new java.awt.Color(102, 255, 204));
        jButtonLogOut.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/logout.png"))); // NOI18N
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButtonLogOut.setIconTextGap(6);
        jButtonLogOut.setPreferredSize(new java.awt.Dimension(117, 47));
        jButtonLogOut.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButtonLogOutAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel3))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jButtonHardware, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHardware, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonManager, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");

        jLabelName.setFont(new java.awt.Font("Bodoni MT Black", 3, 12)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(0, 255, 0));
        jLabelName.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("as");

        jLabelType.setBackground(new java.awt.Color(255, 0, 0));
        jLabelType.setFont(new java.awt.Font("Bodoni MT Black", 3, 12)); // NOI18N
        jLabelType.setForeground(new java.awt.Color(255, 0, 0));
        jLabelType.setText("Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelType, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelName)
                    .addComponent(jLabel5)
                    .addComponent(jLabelType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAddUser.setBackground(new java.awt.Color(0, 153, 153));
        jButtonAddUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddUser.setForeground(new java.awt.Color(153, 153, 0));
        jButtonAddUser.setText("ADD USER");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jLabelpass.setText("pass");

        jButtonSelect.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSelect.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSelect.setForeground(new java.awt.Color(51, 255, 204));
        jButtonSelect.setText("Details");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jButtonSearch.setBackground(new java.awt.Color(0, 0, 51));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(204, 204, 255));
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonAddProduct.setBackground(new java.awt.Color(0, 0, 51));
        jButtonAddProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddProduct.setForeground(new java.awt.Color(255, 255, 153));
        jButtonAddProduct.setText("ADD PRODUCT");
        jButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProductActionPerformed(evt);
            }
        });

        jButtonSellProduct.setBackground(new java.awt.Color(0, 51, 51));
        jButtonSellProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSellProduct.setForeground(new java.awt.Color(255, 204, 51));
        jButtonSellProduct.setText("SELL PRODUCT");
        jButtonSellProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSellProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSelect)
                            .addComponent(jLabelpass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSellProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSearch)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSelect)))
                        .addGap(21, 21, 21)
                        .addComponent(jButtonSellProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabelpass))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManagerActionPerformed
        
        try{  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
            Statement sta = conn.createStatement();  
               
            ResultSet rs = sta.executeQuery("SELECT  ID,Name,Email,Address,Phone FROM Manager");  
            ResultSetMetaData  rsmd = rs.getMetaData(); 
            int  columns = rsmd.getColumnCount();   
            DefaultTableModel dtm = new DefaultTableModel(); 
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
             
            for(int  i= 1; i < columns+1; i++){
                columns_name.addElement (rsmd.getColumnLabel(i));  
            }                 
              
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()){
                data_rows = new Vector(); 
                for (int j = 1; j <columns+1; j++){ 
                    data_rows.addElement(rs.getString(j)) ;
                }  
                dtm.addRow(data_rows);      
            }   
            
            jTable.setModel(dtm);      
        }catch (Exception e){  
            e.printStackTrace();  
         }
        jButtonSelect.setVisible(false);
    
    }//GEN-LAST:event_jButtonManagerActionPerformed

    private void jButtonHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHardwareActionPerformed
        // TODO add your handling code here:
        jButtonSelect.setVisible(true);
        try{  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
            Statement sta = conn.createStatement();  
               
            ResultSet rs = sta.executeQuery("SELECT DISTINCT  ID,Name FROM Hardware");  
            ResultSetMetaData  rsmd = rs.getMetaData(); 
            int  columns = rsmd.getColumnCount();   
            DefaultTableModel dtm = new DefaultTableModel(); 
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
             
            for(int  i= 1; i < columns+1; i++){
                columns_name.addElement (rsmd.getColumnLabel(i));  
            }                 
              
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()){
                data_rows = new Vector(); 
                for (int j = 1; j <columns+1; j++){ 
                    data_rows.addElement(rs.getString(j)) ;
                }  
                dtm.addRow(data_rows);      
            }   
            
            jTable.setModel(dtm);      
        }catch (Exception e){  
            e.printStackTrace();  
         }
        
    }//GEN-LAST:event_jButtonHardwareActionPerformed

    private void jButtonCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculatorActionPerformed
        // TODO add your handling code here:
        new Calculator().setVisible(true);
        
    }//GEN-LAST:event_jButtonCalculatorActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        try{  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
            Statement sta = conn.createStatement();  
               
            ResultSet rs = sta.executeQuery("SELECT  ID,Name,Email,Address,Phone FROM Customer");  
            ResultSetMetaData  rsmd = rs.getMetaData(); 
            int  columns = rsmd.getColumnCount();   
            DefaultTableModel dtm = new DefaultTableModel(); 
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
             
            for(int  i= 1; i < columns+1; i++){
                columns_name.addElement (rsmd.getColumnLabel(i));  
            }                 
              
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()){
                data_rows = new Vector(); 
                for (int j = 1; j <columns+1; j++){ 
                    data_rows.addElement(rs.getString(j)) ;
                }  
                dtm.addRow(data_rows);      
            }   
            
            jTable.setModel(dtm);      
        }catch (Exception e){  
            e.printStackTrace();  
         }
        jButtonSelect.setVisible(false);
      
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        try{  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
            Statement sta = conn.createStatement();  
               
            ResultSet rs = sta.executeQuery("SELECT  Id,Name,Email,Address,Phone FROM Employee");  
            ResultSetMetaData  rsmd = rs.getMetaData(); 
            int  columns = rsmd.getColumnCount();   
            DefaultTableModel dtm = new DefaultTableModel(); 
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
             
            for(int  i= 1; i < columns+1; i++){
                columns_name.addElement (rsmd.getColumnLabel(i));  
            }                 
              
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()){
                data_rows = new Vector(); 
                for (int j = 1; j <columns+1; j++){ 
                    data_rows.addElement(rs.getString(j)) ;
                }  
                dtm.addRow(data_rows);      
            }   
            
            jTable.setModel(dtm);      
        }catch (Exception e){  
            e.printStackTrace();  
         } 
        jButtonSelect.setVisible(false);
    
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonLogOutAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButtonLogOutAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLogOutAncestorAdded

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        // TODO add your handling code here:
        String type = jLabelType.getText();
        Registration reg = new Registration();
        reg.jLabelType.setText(type);
        reg.setVisible(true);
        
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangePasswordActionPerformed
        // TODO add your handling code here:
        String password = jLabelpass.getText();
        String name = jLabelName.getText();
        String type = jLabelType.getText();
        
        ChangePassword changepassword = new ChangePassword();
        changepassword.jLabelpass.setText(password);
        changepassword.jLabelname.setText(name);
        changepassword.jLabeltype.setText(type);
        changepassword.setVisible(true);
    }//GEN-LAST:event_jButtonChangePasswordActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        // TODO add your handling code here:
        TableModel model1 = jTable.getModel();
        
        int[] index = jTable.getSelectedRows();
        Object[] row = new Object[5];
        Object[] temp = new Object[2];
        
        //DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
        
        for(int k=0; k<index.length;k++){
            temp[0]=model1.getValueAt(index[k],1);
            String name = String.valueOf(temp[0]);
            //System.out.println(name);
            
            DetailsTable details = new DetailsTable();
            details.jLabelName.setText(name);
            try{  
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
                Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
                Statement sta = conn.createStatement();  
            
                
                    ResultSet rs = sta.executeQuery("USE Hardwaremanagementshop SELECT  Model,Code,Quantity,Price FROM Hardware WHERE Name = '"+name+"' ");  
                    ResultSetMetaData  rsmd = rs.getMetaData(); 
                    int  columns = rsmd.getColumnCount();   
                    DefaultTableModel dtm = new DefaultTableModel(); 
                    Vector columns_name=new Vector();
                    Vector data_rows=new Vector();
             
                    for(int  i= 1; i < columns+1; i++){
                        columns_name.addElement (rsmd.getColumnLabel(i));  
                    }                 
              
                    dtm.setColumnIdentifiers(columns_name);
            
                    while (rs.next()){
                        data_rows = new Vector(); 
                        for (int j = 1; j <columns+1; j++){ 
                        data_rows.addElement(rs.getString(j)) ;
                        }  
                        dtm.addRow(data_rows);      
                    }   
                    details.jTableDetails.setModel(dtm);   
                
                /*if(temp[0].equals("Monitor")){
                    ResultSet rs = sta.executeQuery("USE Hardwaremanagementshop SELECT  Model,Code,Quantity,Price FROM Hardware");  
                    ResultSetMetaData  rsmd = rs.getMetaData(); 
                    int  columns = rsmd.getColumnCount();   
                    DefaultTableModel dtm = new DefaultTableModel(); 
                    Vector columns_name=new Vector();
                    Vector data_rows=new Vector();
             
                    for(int  i= 1; i < columns+1; i++){
                        columns_name.addElement (rsmd.getColumnLabel(i));  
                    }                 
              
                    dtm.setColumnIdentifiers(columns_name);
            
                    while (rs.next()){
                        data_rows = new Vector(); 
                        for (int j = 1; j <columns+1; j++){ 
                        data_rows.addElement(rs.getString(j)) ;
                        }  
                        dtm.addRow(data_rows);      
                    }   
                    details.jTableDetails.setModel(dtm);   
                }
                
                if(temp[0].equals("Motherboard")){
                    ResultSet rs = sta.executeQuery("USE Hardwaremanagementshop SELECT  Model,Code,Quantity,Price FROM Hardware");  
                    ResultSetMetaData  rsmd = rs.getMetaData(); 
                    int  columns = rsmd.getColumnCount();   
                    DefaultTableModel dtm = new DefaultTableModel(); 
                    Vector columns_name=new Vector();
                    Vector data_rows=new Vector();
             
                    for(int  i= 1; i < columns+1; i++){
                        columns_name.addElement (rsmd.getColumnLabel(i));  
                    }                 
              
                    dtm.setColumnIdentifiers(columns_name);
            
                    while (rs.next()){
                        data_rows = new Vector(); 
                        for (int j = 1; j <columns+1; j++){ 
                        data_rows.addElement(rs.getString(j)) ;
                        }  
                        dtm.addRow(data_rows);      
                    }   
                    details.jTableDetails.setModel(dtm);   
                }*/
                
        }catch (Exception e){  
            e.printStackTrace();  
         }
                
        details.setVisible(true);
        }
        
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String search = jTextFieldSearch.getText();
        try{  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=HardwareManagementShop;user=Jitu;password=shatu");
            Statement sta = conn.createStatement();  
               
            ResultSet rs = sta.executeQuery("SELECT  Name, Model, Code, Quantity, Price FROM Hardware WHERE Hardware.Name LIKE '"+search+"%' ORDER BY Name ");  
            ResultSetMetaData  rsmd = rs.getMetaData(); 
            int  columns = rsmd.getColumnCount();   
            DefaultTableModel dtm = new DefaultTableModel(); 
            Vector columns_name=new Vector();
            Vector data_rows=new Vector();
             
            for(int  i= 1; i < columns+1; i++){
                columns_name.addElement (rsmd.getColumnLabel(i));  
            }                 
              
            dtm.setColumnIdentifiers(columns_name);
            
            while (rs.next()){
                data_rows = new Vector(); 
                for (int j = 1; j <columns+1; j++){ 
                    data_rows.addElement(rs.getString(j)) ;
                }  
                dtm.addRow(data_rows);      
            }   
            
            jTable.setModel(dtm);      
        }catch (Exception e){  
            e.printStackTrace();  
         }
        
        //String sql="use HardwareManagementShop select * from hardware where hardware.Name='"+search+"'";
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProductActionPerformed
        // TODO add your handling code here:
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_jButtonAddProductActionPerformed

    private void jButtonSellProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSellProductActionPerformed
        // TODO add your handling code here:
        new SellProduct().setVisible(true);
    }//GEN-LAST:event_jButtonSellProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAddProduct;
    public javax.swing.JButton jButtonAddUser;
    public javax.swing.JButton jButtonCalculator;
    public javax.swing.JButton jButtonChangePassword;
    public javax.swing.JButton jButtonCustomer;
    public javax.swing.JButton jButtonEmployee;
    public javax.swing.JButton jButtonHardware;
    public javax.swing.JButton jButtonLogOut;
    public javax.swing.JButton jButtonManager;
    private javax.swing.JButton jButtonSearch;
    public javax.swing.JButton jButtonSelect;
    public javax.swing.JButton jButtonSellProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelName;
    public javax.swing.JLabel jLabelType;
    public javax.swing.JLabel jLabelpass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldSearch;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    // End of variables declaration//GEN-END:variables
}
