/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hardwaremanagementshop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shatu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        jTextFieldUserName.setBackground(new java.awt.Color(153, 255, 204));
        jTextFieldUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameActionPerformed(evt);
            }
        });

        jPasswordFieldPassword.setBackground(new java.awt.Color(153, 255, 204));
        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 51));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(102, 255, 102));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jComboBox.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jComboBox.setForeground(new java.awt.Color(102, 0, 0));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Employee", "Customer" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hardwaremanagementshop/Login.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Computer Hardware Management Shop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogin)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTextFieldUserName))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonLogin)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        
        ConnectSQL connect = new ConnectSQL();
        Connection conn = null;
        Statement sta = null;
        String username = jTextFieldUserName.getText();
        String password = jPasswordFieldPassword.getText();
        
        try{
            
            conn = connect.getConnect();
            System.out.println("Connect: "+connect.getConnect());
            //PreparedStatement ps = conn.PrepareStatement("select * customer where name = ? and password = ? ");   
        }catch(Exception e){
            System.out.println("Database Not Connected") ;
        }
        try{
            sta = conn.createStatement();
            System.out.println("Statement: "+conn.createStatement());
        }catch(Exception e){
            System.out.println("Statement Creation Problem");
        }
        
        /*try{
            System.out.println(username+"\n"+password);
            String query = "USE HardwareManagementShop SELECT * FROM Customer WHERE Name = '"+username+"' AND Password = '"+password+"'";
            ResultSet rs = sta.executeQuery(query); 
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                JOptionPane.showMessageDialog(null, "Successfully LOGIN");
                this.setVisible(false);
            }else{
                System.out.println("Catch 1");
                JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
            }
        }catch(Exception e){
            System.out.println("Catch 2");
            JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
        }*/
        
        String choice = jComboBox.getSelectedItem()+"";
        //String pass = String.valueOf(jPasswordFieldPassword.getPassword());
      
        //For CUSTOMER:
        if(choice.equalsIgnoreCase("Customer")){
            try{
            System.out.println(username+"\n"+password);
            String query = "USE HardwareManagementShop SELECT * FROM Customer WHERE Name = '"+username+"' AND Password = '"+password+"'";
            ResultSet rs = sta.executeQuery(query); 
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                JOptionPane.showMessageDialog(null, "Successfully LOGIN as CUSTOMER");
                Home home = new Home();
                home.jLabelType.setText(choice);
                home.jLabelName.setText(username);
                home.jLabelpass.setText(password);
                home.jButtonHardware.setEnabled(true);
                home.jButtonCalculator.setEnabled(true);
                home.jButtonManager.setEnabled(false);
                home.jButtonEmployee.setEnabled(false);
                home.jButtonAddProduct.setEnabled(false);
                home.jButtonSellProduct.setEnabled(false);
                home.jButtonChangePassword.setEnabled(true);
                home.jButtonLogOut.setEnabled(true);
                home.jButtonAddUser.setEnabled(false);
                home.setVisible(true);
                this.setVisible(false);
            
            }else{
                JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
            }
        }catch(Exception e){
            System.out.println("Catch Exception");
            JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
         }       
        }
        
        //For MANAGER:
        else if(choice.equalsIgnoreCase("Manager")){
            try{
            System.out.println(username+"\n"+password);
            String query = "USE HardwareManagementShop SELECT * FROM Manager WHERE Name = '"+username+"' AND Password = '"+password+"'";
            ResultSet rs = sta.executeQuery(query); 
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                JOptionPane.showMessageDialog(null, "Successfully LOGIN as MANAGER");
                Home home = new Home();
                home.jLabelType.setText(choice);
                home.jLabelName.setText(username);
                home.jLabelpass.setText(password);
                home.setVisible(true);
                this.setVisible(false);
            }else{
                System.out.println("Catch 1");
                JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
            }
        }catch(Exception e){
            System.out.println("Catch 2");
            JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
         }  
        }
        
        //For EMPLOYEE:
        if(choice.equalsIgnoreCase("Employee")){
            try{
            System.out.println(username+"\n"+password);
            String query = "USE HardwareManagementShop SELECT * FROM Employee WHERE Name = '"+username+"' AND Password = '"+password+"'";
            ResultSet rs = sta.executeQuery(query); 
            int n=0;
            while(rs.next()){
                n++;
            }
            if(n>0){
                JOptionPane.showMessageDialog(null, "Successfully LOGIN as EMPLOYEE");
                Home home = new Home();
                home.jLabelType.setText(choice);
                home.jLabelName.setText(username);
                home.jLabelpass.setText(password);
                home.jButtonAddProduct.setEnabled(false);
                home.jButtonHardware.setEnabled(true);
                home.jButtonCalculator.setEnabled(true);
                home.jButtonManager.setEnabled(true);
                home.jButtonEmployee.setEnabled(true);
                home.jButtonChangePassword.setEnabled(true);
                home.jButtonLogOut.setEnabled(true);
                home.setVisible(true);
                this.setVisible(false);
            
            }else{
                System.out.println("Catch 1");
                JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
            }
        }catch(Exception e){
            System.out.println("Catch 2");
            JOptionPane.showMessageDialog(null, "Wrong User Name Or Password");
         }       
        }
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jTextFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
